CREATE TABLE user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    person_id VARCHAR(255) UNIQUE NOT NULL,
    uuid VARCHAR(255) UNIQUE NOT NULL
);
