
CREATE TABLE user_registry (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               name VARCHAR(255) NOT NULL,
                               surname VARCHAR(255),
                               person_id VARCHAR(12) NOT NULL,
                               uuid VARCHAR(255) NOT NULL,
                               PRIMARY KEY (id)
);

ALTER TABLE user_registry ADD CONSTRAINT unique_person_id UNIQUE (person_id);
ALTER TABLE user_registry ADD CONSTRAINT unique_uuid UNIQUE (uuid);